apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctsefrontend
  name: ctsefrontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctsefrontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctsefrontend
    spec:
      containers:
        # - image: it19062266/ctse:latest
        - image: it19062266/ctse:{{tag}}
          imagePullPolicy: Always
          name: ctse
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30