apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctsefrontend
  name: ctsefrontend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: ctsefrontend
status:
  loadBalancer: {}